[build]
  command = "npm run build"
  publish = "build"
  environment = { CI = "false" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
from = "/*"
to = "/index.html"
status = 200